spring:
  profiles:
    active: development
---
server:
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: cloud
security.ignored: /resources/**
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://10.255.8.51:3306/zhouyang_event_sourcing
    username: root
    password: tzj
    initialize: true
security.ignored: /resources/**
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
security.ignored: /resources/**
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
